import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
blur = true
dynamic_padding = false
opacity = 0.7

[window.padding]
x = 15
y = 15

[font]
size = 12.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

